# Generated by Django 3.0.5 on 2020-05-26 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200526_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
