# Generated by Django 3.0.5 on 2020-05-26 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200526_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateField(default=datetime.datetime.today, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateField(default=datetime.datetime.today, editable=False),
        ),
    ]
